Document: zabbix-pgmonz
Title: Debian zabbix-pgmonz Manual
Author: <insert document author here>
Abstract: This manual describes what zabbix-pgmonz is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zabbix-pgmonz/zabbix-pgmonz.sgml.gz

Format: postscript
Files: /usr/share/doc/zabbix-pgmonz/zabbix-pgmonz.ps.gz

Format: text
Files: /usr/share/doc/zabbix-pgmonz/zabbix-pgmonz.text.gz

Format: HTML
Index: /usr/share/doc/zabbix-pgmonz/html/index.html
Files: /usr/share/doc/zabbix-pgmonz/html/*.html
