Document: zabbix-check-javaproc
Title: Debian zabbix-check-javaproc Manual
Author: <insert document author here>
Abstract: This manual describes what zabbix-check-javaproc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zabbix-check-javaproc/zabbix-check-javaproc.sgml.gz

Format: postscript
Files: /usr/share/doc/zabbix-check-javaproc/zabbix-check-javaproc.ps.gz

Format: text
Files: /usr/share/doc/zabbix-check-javaproc/zabbix-check-javaproc.text.gz

Format: HTML
Index: /usr/share/doc/zabbix-check-javaproc/html/index.html
Files: /usr/share/doc/zabbix-check-javaproc/html/*.html
