Document: zabbix-cdh-rm
Title: Debian zabbix-cdh-rm Manual
Author: <insert document author here>
Abstract: This manual describes what zabbix-cdh-rm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zabbix-cdh-rm/zabbix-cdh-rm.sgml.gz

Format: postscript
Files: /usr/share/doc/zabbix-cdh-rm/zabbix-cdh-rm.ps.gz

Format: text
Files: /usr/share/doc/zabbix-cdh-rm/zabbix-cdh-rm.text.gz

Format: HTML
Index: /usr/share/doc/zabbix-cdh-rm/html/index.html
Files: /usr/share/doc/zabbix-cdh-rm/html/*.html
