Document: zabbix-aerospike
Title: Debian zabbix-aerospike Manual
Author: <insert document author here>
Abstract: This manual describes what zabbix-aerospike is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zabbix-aerospike/zabbix-aerospike.sgml.gz

Format: postscript
Files: /usr/share/doc/zabbix-aerospike/zabbix-aerospike.ps.gz

Format: text
Files: /usr/share/doc/zabbix-aerospike/zabbix-aerospike.text.gz

Format: HTML
Index: /usr/share/doc/zabbix-aerospike/html/index.html
Files: /usr/share/doc/zabbix-aerospike/html/*.html
